// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelWarrants.Models;

#nullable disable

namespace TravelWarrants.Migrations
{
    [DbContext(typeof(TravelWarrantsContext))]
    [Migration("20230620132125_DatabaseCreation")]
    partial class DatabaseCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelWarrants.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("ClientId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InoviceId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InoviceId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Excursion")
                        .HasColumnType("boolean");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNUmber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VAT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PTT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VAT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.CompanyGiroAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompaniesGiroAccounts", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NUmberOfPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Inovice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CurrencyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description1")
                        .HasColumnType("text");

                    b.Property<string>("Description2")
                        .HasColumnType("text");

                    b.Property<string>("Description3")
                        .HasColumnType("text");

                    b.Property<string>("Description4")
                        .HasColumnType("text");

                    b.Property<string>("Description5")
                        .HasColumnType("text");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Inovice1")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NoVAT")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("NumberOfDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OfferAccepted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price1")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price2")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price4")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price5")
                        .HasColumnType("numeric");

                    b.Property<bool?>("PriceWithoutVAT")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ProinoviceWithoutVAT")
                        .HasColumnType("boolean");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<int>("Service1")
                        .HasColumnType("integer");

                    b.Property<int?>("Service2")
                        .HasColumnType("integer");

                    b.Property<int?>("Service3")
                        .HasColumnType("integer");

                    b.Property<int?>("Service4")
                        .HasColumnType("integer");

                    b.Property<int?>("Service5")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAT")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAT1")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VAT2")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VAT3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VAT4")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VAT5")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Value1")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Value2")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Value3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Value4")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Value5")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Service1");

                    b.HasIndex("Service2");

                    b.HasIndex("Service3");

                    b.HasIndex("Service4");

                    b.HasIndex("Service5");

                    b.ToTable("Inovices", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.InoviceService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InoviceId")
                        .HasColumnType("integer");

                    b.Property<string>("NumberOfDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VAT")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InoviceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("InovicesServices", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Places", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VATRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOfAccount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountOfDeposit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Statuses", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DepartureLatitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DepartureLongitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DestinationLatitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DestinationLongitude")
                        .HasColumnType("numeric");

                    b.Property<int?>("DriverId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<decimal>("EndMileage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Fuel")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FuelPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("IntermediateDestinations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Mileage")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("NumberOfDays")
                        .HasColumnType("numeric");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StartMileage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeOfTour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Toll")
                        .HasColumnType("numeric");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VehicleMileage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Tours", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Change")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FuelConsumption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberOfSeats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("TravelWarrants.Models.Account", b =>
                {
                    b.HasOne("TravelWarrants.Models.Client", "Client")
                        .WithMany("Account")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWarrants.Models.Inovice", "Inovice")
                        .WithMany("Account")
                        .HasForeignKey("InoviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Inovice");
                });

            modelBuilder.Entity("TravelWarrants.Models.CompanyGiroAccount", b =>
                {
                    b.HasOne("TravelWarrants.Models.Company", "Company")
                        .WithMany("CompanyGiroAccount")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TravelWarrants.Models.Inovice", b =>
                {
                    b.HasOne("TravelWarrants.Models.Client", "Client")
                        .WithMany("Inovice")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWarrants.Models.Service", "Service")
                        .WithMany("Inovice")
                        .HasForeignKey("Service1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWarrants.Models.Service", "Service6")
                        .WithMany("Inovice1")
                        .HasForeignKey("Service2");

                    b.HasOne("TravelWarrants.Models.Service", "Service7")
                        .WithMany("Inovice2")
                        .HasForeignKey("Service3");

                    b.HasOne("TravelWarrants.Models.Service", "Service8")
                        .WithMany("Inovice3")
                        .HasForeignKey("Service4");

                    b.HasOne("TravelWarrants.Models.Service", "Service9")
                        .WithMany("Inovice4")
                        .HasForeignKey("Service5");

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Service6");

                    b.Navigation("Service7");

                    b.Navigation("Service8");

                    b.Navigation("Service9");
                });

            modelBuilder.Entity("TravelWarrants.Models.InoviceService", b =>
                {
                    b.HasOne("TravelWarrants.Models.Inovice", "Inovice")
                        .WithMany("InoviceService")
                        .HasForeignKey("InoviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelWarrants.Models.Service", "Service")
                        .WithMany("InoviceService")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inovice");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TravelWarrants.Models.Payment", b =>
                {
                    b.HasOne("TravelWarrants.Models.Client", "Client")
                        .WithMany("Payment")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TravelWarrants.Models.Status", b =>
                {
                    b.HasOne("TravelWarrants.Models.Client", "Client")
                        .WithMany("Status")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TravelWarrants.Models.Tour", b =>
                {
                    b.HasOne("TravelWarrants.Models.Client", "Client")
                        .WithMany("Tour")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWarrants.Models.Driver", "Driver")
                        .WithMany("Tour")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelWarrants.Models.Vehicle", "Vehicle")
                        .WithMany("Tour")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TravelWarrants.Models.Client", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Inovice");

                    b.Navigation("Payment");

                    b.Navigation("Status");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelWarrants.Models.Company", b =>
                {
                    b.Navigation("CompanyGiroAccount");
                });

            modelBuilder.Entity("TravelWarrants.Models.Driver", b =>
                {
                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelWarrants.Models.Inovice", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("InoviceService");
                });

            modelBuilder.Entity("TravelWarrants.Models.Service", b =>
                {
                    b.Navigation("Inovice");

                    b.Navigation("Inovice1");

                    b.Navigation("Inovice2");

                    b.Navigation("Inovice3");

                    b.Navigation("Inovice4");

                    b.Navigation("InoviceService");
                });

            modelBuilder.Entity("TravelWarrants.Models.Vehicle", b =>
                {
                    b.Navigation("Tour");
                });
#pragma warning restore 612, 618
        }
    }
}
